export const
    DOUBLE_COUNTER = 'counter/DOUBLE_COUNTER',
    SET_COUNTER = 'counter/SET_COUNTER',
    /*
    * start from here
    * */
    MATCH_TYPE_SETTER_FOR_FILTER='auth-less/MATCH_TYPE_SETTER_FOR_FILTER',
    MATCH_TYPE = 'auth-less/MATCH_TYPE',
    UPCOMING_MATCH_LIST = 'auth-less/UPCOMING_MATCH_LIST',
    UPCOMING_MATCH_LIST_FOOTBALL = 'auth-less/UPCOMING_MATCH_LIST_FOOTBALL',
    UPCOMING_MATCH_LIST_CRICKET = 'auth-less/UPCOMING_MATCH_LIST_CRICKET';
