export const
    DOUBLE_COUNTER = 'counter/DOUBLE_COUNTER',
    SET_COUNTER = 'counter/SET_COUNTER',
    /*
    * start from here
    * */
    TOURNAMENT_ID_SETTER = 'auth-less/TOURNAMENT_ID_SETTER',
    TOURNAMENT_ID_GETTER = 'auth-less/TOURNAMENT_ID_GETTER',
    TOURNAMENT_ID_NAME_MAP = 'auth-less/TOURNAMENT_ID_NAME_MAP',
    MATCH_TYPE_SETTER_FOR_FILTER = 'auth-less/MATCH_TYPE_SETTER_FOR_FILTER',
    MATCH_TYPE = 'auth-less/MATCH_TYPE',
    UPCOMING_MATCH_LIST = 'auth-less/UPCOMING_MATCH_LIST',
    MATCH_BY_MATCH_ID = 'auth-less/MATCH_BY_MATCH_ID',
    UPCOMING_MATCH_LIST_FOOTBALL = 'auth-less/UPCOMING_MATCH_LIST_FOOTBALL',
    UPCOMING_MATCH_LIST_CRICKET = 'auth-less/UPCOMING_MATCH_LIST_CRICKET',
    USER_LOGIN = 'auth/USER_LOGIN',
    USER_LOGIN_STATUS = 'auth/USER_LOGIN_STATUS',
    USER_LOGOUT = 'auth/USER_LOGOUT',
    TOKEN_UPDATE = 'auth/USER_LOGOUT'

;
